### ISSUE TITLE
composeApp:iosArm64Main: Could not find org.jetbrains.kotlinx.multiplatform-library-template:alert-kmp-iosarm64:0.0.1.

### ISSUE THREAD

**Issue by GabrielRealTime** [KhubaibKhan4/Flexi-Store-KMP#4]
:composeApp:iosArm64Main: Could not find org.jetbrains.kotlinx.multiplatform-library-template:alert-kmp-iosarm64:0.0.1.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/multiplatform-library-template/alert-kmp-iosarm64/0.0.1/alert-kmp-iosarm64-0.0.1.pom
  - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/multiplatform-library-template/alert-kmp-iosarm64/0.0.1/alert-kmp-iosarm64-0.0.1.pom
Required by:
    project :composeApp > io.github.khubaibkhan4:alert-kmp:0.0.7

**Comment by KhubaibKhan4** [comment]
This issue usually occurs on the Apple Chips Devices but works fine on all the Intel chips. I'll fix it asap. If you have any suggestions, Please let me know

**Comment by pkdhankher** [comment]
Hi @KhubaibKhan4, I'm also facing this issue, unable to build IOS. Is this issue resolved?

**Comment by KhubaibKhan4** [comment]
Just received my new Mac. This issue will be fixed asap.

**Comment by pkdhankher** [comment]
looking forward to your response @KhubaibKhan4

**Comment by KhubaibKhan4** [comment]
@pkdhankher This issue has been fixed.

**Comment by pkdhankher** [comment]
@KhubaibKhan4 Could you please mention the exact fix here?

**Comment by KhubaibKhan4** [comment]
This issue was due to the iosArm64 Target. I was trying to build and publish a new version using Windows and an old MacBook with an intel chip. Now, I just updated it with the MacBook M2, now it works fine.

**Comment by pkdhankher** [comment]
Got it, please mention the exact changes or your commit reference. 

Thanks in advance.
